In [4]:
1+7

8

In [5]:
2*4

8

In [6]:
# A first example
print(1+1)

"""
A first example 
with a longer comment
"""

2


'\nA first example \nwith a longer comment\n'

In [7]:
# Empty spaces
3 + 4

7

In [8]:
# Assignments
a = 3
bb = 4

a

bb

4

In [9]:
a, bb = 3, 4

In [10]:
2.7 * a

8.100000000000001

In [11]:
# The exponation operator is ** in Python instead of ^ as in most other programming languages 
a**2

9

In [12]:
a/bb

0.75

In [13]:
# Case sensitive
A

NameError: name 'A' is not defined

In [14]:
3a

SyntaxError: invalid decimal literal (1838723517.py, line 1)

In [15]:
# Simple lists

z_1 = [3, 4, 4.5, -2, 7]

z_1

z_2 = [1, 2, 3, 4, 5]

print(z_2)



mixed = [2, 'sad', 5.3, 'YES', "beautiful", "sad"]

mixed

[1, 2, 3, 4, 5]


[2, 'sad', 5.3, 'YES', 'beautiful', 'sad']

In [16]:
# module numpy


import numpy

numpy.sqrt(2)


import numpy as np

np.sqrt(2)



from numpy import sqrt

sqrt(2)

1.4142135623730951

In [17]:
# Vectors

import numpy as np

x = np.array([2, 1, 4, 5, -8])

x

array([ 2,  1,  4,  5, -8])

In [18]:
x[3]

5

In [19]:
x*x

array([ 4,  1, 16, 25, 64])

In [20]:
x = np.linspace(start=1, stop=2 ,num=5)

x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
y = np.arange(start=1, stop=7, step=.6)

y


array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4])

In [22]:
z = np.arange(start=2, stop=9)

z

array([2, 3, 4, 5, 6, 7, 8])

In [23]:
w = np.arange(9)

w

array([0, 1, 2, 3, 4, 5, 6, 7, 8])