# SW 02

In [9]:
# Beispiel likelihood   
import numpy as np
likelihood = np.linspace(0,1,11)
likelihood

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
# Beispiel Prior
y = np.array([0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0])
prior = y/np.sum(y) # --> macht eine Wahrscheinlichkeitsverteilung aus den Wetrten aus y
prior

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.16, 0.12, 0.08, 0.04, 0.  ])

In [11]:
# Beipiel Margin
margin = np.sum(prior * likelihood)
margin

0.5

In [12]:
# Beispiel Posterioir
post = prior * likelihood / margin
post

array([0.   , 0.008, 0.032, 0.072, 0.128, 0.2  , 0.192, 0.168, 0.128,
       0.072, 0.   ])