# Type I Error

We assume that the null hypothesis is true. 

In [63]:
import scipy.stats as st
import numpy as np
np.set_printoptions(precision=3,suppress=True)

In [76]:
# Significance level
alpha = 0.05

# Number of rows and columns of matrix A
r = 5
c = 10

# Produces r*c normally random numbers with μ = 0 and σ = 1
A = st.norm.rvs(size=r*c)
print("Random numbers as vector","\n\n", A,"\n")

# Reshape A into a (r x c)-matrix
A = A.reshape((r,c))
print("Random numbers as matrix","\n\n", A,"\n")

# Takes t-test of all columns with with popmean=0, i.e. null hypothesis is true because data μ = 0
b = st.ttest_1samp(a=A, popmean=0).pvalue
print("p-values of columns","\n\n", b,"\n")

# Number of p-values less than α
print("Number of p-values less than α (null hypotesis H_0 is wrongly rejected)","\n\n", np.sum(b < alpha))

Random numbers as vector 

 [-0.148  0.456 -0.492  2.299 -2.13   0.171  1.103  1.768 -0.945 -0.793
 -1.538  1.086 -0.121  0.934 -1.58   0.421 -0.325  0.766 -1.511  1.234
 -0.35   1.519 -1.048  0.226  0.739 -0.475  0.986 -0.497 -1.058 -1.837
  0.927  0.07   0.44   1.153  0.718 -0.857 -0.785  1.     0.304  2.072
 -0.389 -0.284 -0.884  0.267  0.635 -0.942 -0.601 -0.108 -2.47   0.445] 

Random numbers as matrix 

 [[-0.148  0.456 -0.492  2.299 -2.13   0.171  1.103  1.768 -0.945 -0.793]
 [-1.538  1.086 -0.121  0.934 -1.58   0.421 -0.325  0.766 -1.511  1.234]
 [-0.35   1.519 -1.048  0.226  0.739 -0.475  0.986 -0.497 -1.058 -1.837]
 [ 0.927  0.07   0.44   1.153  0.718 -0.857 -0.785  1.     0.304  2.072]
 [-0.389 -0.284 -0.884  0.267  0.635 -0.942 -0.601 -0.108 -2.47   0.445]] 

p-values of columns 

 [0.487 0.158 0.192 0.061 0.635 0.285 0.86  0.22  0.065 0.764] 

Number of p-values less than α (null hypotesis H_0 is wrongly rejected) 

 0


In [78]:
# Significance level
alpha = 0.01

# Number of rows and columns of matrix A
r = 100
c = 10000

for i in range(100):
    A = st.norm.rvs(size=r*c)
    A = A.reshape((r,c))
    b = st.ttest_1samp(a=A, popmean=0).pvalue
    print(np.sum(b < alpha), end=" ")

105 91 97 95 102 100 117 102 74 103 109 113 91 84 96 97 102 101 122 104 101 106 118 106 96 108 112 100 84 112 95 84 100 120 95 118 113 100 102 109 103 96 108 90 101 89 106 105 106 120 109 96 102 95 84 103 115 110 88 81 109 104 121 106 111 84 101 101 93 92 88 99 118 127 78 112 119 110 96 106 93 117 113 99 103 97 103 85 102 103 92 102 95 117 122 100 102 85 105 120 