In [1]:
# Likelyhood verteilung:
import numpy as np

likeli = np.linspace(0,1,11) 
likeli

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
# symmetrische Prior verteilung:
y = np.array([0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0])

prior = y/np.sum(y) 
prior

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.16, 0.12, 0.08, 0.04, 0.  ])

In [3]:
# Randwahrscheinlichkeit:
margin = np.sum(prior * likeli) 
margin

0.5

In [4]:
# Posterior verteilung:
post = prior * likeli / margin 
post

array([0.   , 0.008, 0.032, 0.072, 0.128, 0.2  , 0.192, 0.168, 0.128,
       0.072, 0.   ])

In [14]:
#Sensitivität P(+|M)
sens = 0.917
#Spezifität P(-|M quer)
spez = 0.935

prior = 0.03 # P(M) --> W'keit, dass eine Person erkrankt ist

# 2x positives ergebnis: 
def post_pos(prior):
    post = (sens*prior) / (sens*prior + (1-spez)*(1-prior))
    return post

# positives, dann negatives ergebnis: 
def post_neg(prior):
    post = (1-sens)*prior / ((1-sens)*prior + spez*(1-prior))
    return post

post_neg(0.03) # wahrscheinlichkeit, dass eine Person erkrankt ist, positives, dann negatives ergebnis hat --> 02%

0.002737948627726951